spring.application.name=paymentApp
spring.datasource.url=jdbc:postgresql://localhost:5432/vaultshare
spring.datasource.username=vault
spring.datasource.password=vaultpass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
